### PR TITLE
Fix license tag in Cabal file

### PR DESCRIPTION
**Pull request by peti**
Synchronize the declared license with the de-facto one from https://github.com/ekmett/groupoids/commit/36e89f881aa3daaaf19d7cc15ca82c83ed31062a.

### CODE REVIEW

**Comment by ekmett** [comment]
Doing so will require a bump on the cabal version I think.

**Comment by ekmett** [comment]
OTOH, given that this package is just a stub with no content I suppose its pretty easily done.

**Comment by ekmett** [comment]
In theory we can flag the cabal file as "OtherLicense", which was the recommended encoding before er.. I think it was cabal 1.24 when these were added?

**Comment by ekmett** [comment]
Would that break your tooling / requirements?

**Comment by ekmett** [comment]
Er looks like it was Cabal-1.20

**Comment by ekmett** [comment]
Checking the behavior of this if we just give an "illegal" license tag on pre-1.20. If it lets the user build, I'd be okay with it.

**Comment by ekmett** [comment]
Looks like it only warns. I'm okay with that.

**Comment by ekmett** [comment]
I'll officially happily take patches of this sort for all of my BSD2 packages and just convert them to this style as I find them.

**Comment by peti** [comment]
OK, I'll contribute more PRs if I find more mismatches. Thank you for the quick response!

**Pull request merged**
